# Site settings
title: Tensor Cell
subtitle: 还要再走500里
description: 博客描述
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pangz.me" # 你的域名
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: reasonpun@gmail.com

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: /
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about
  - page: 历史
    directory: history/
    icon: icon-history
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Matei Zaharia
    url: http://people.csail.mit.edu/matei/
  - title: tensorflow
    url: https://github.com/tensorflow/tensorflow
